SERVICE_NAME: "Test solidity"
PORT: 3000
NETWORK: redB
CONTRACTS:
  - name: SingleStorage
    address: ''
  - name: StructStorage
    address: ''
LOG_LEVELS:
  LOG_LEVEL_SYSTEM: 'debug'
  LOG_LEVEL_FILE: 'info'